/**********************************************************************************************************************
 * \file DrvAdc.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include"DrvAdc.h"
#include "IfxVadc.h"
#include "IfxVadc_Adc.h"

typedef struct
{
    IfxVadc_Adc vadc; /*VADC handle*/
    IfxVadc_Adc_Group adcGroup;
} App_VadcAutoScan;

static void DrvAdc_Group0Init(void);
static void DrvAdc_Group0ChannelInit(uint8 param_ChNum);

//Variables
App_VadcAutoScan g_VadcAutoScan;

IfxVadc_Adc_Channel adc0Channel[ADC_GROUP0_MAX];

SensorAdcRaw stSensorAdcRaw; //ADC Raw 값 받을 변수

void DrvAdcInit(void)
{
    DrvAdc_Group0Init();
}

static void DrvAdc_Group0Init(void)
{
    /*create configuration*/

    IfxVadc_Adc_Config adcConfig;
    IfxVadc_Adc_initModuleConfig(&adcConfig, &MODULE_VADC);

    //Initialize module
    IfxVadc_Adc_initGroupConfig(&g_VadcAutoScan.vadc, &adcConfig);

    /*create group config*/
    IfxVadc_Adc_GroupConfig adcGroupConfig;
    IfxVadc_Adc_initGroupConfig(&adcGroupConfig, &g_VadcAutoScan.vadc);

    /*with group 0*/
    adcGroupConfig.groupId = IfxVadc_GroupId_0;
    adcGroupConfig.master = adcGroupConfig.groupId;

    /*enable scan source*/
    adcGroupConfig.arbiter.requestSlotBackgroundScanEnabled = TRUE;

    /*enable auto scan*/
    adcGroupConfig.scanRequest.autoscanEnabled = TRUE;

    /*enable all gates in "always" mode (no edge detection"*/
    adcGroupConfig.scanRequest.triggerConfig.gatingMode = 1;

    /*Initialize the group*/
    /*IfxVadc_Adc_Group_adcGroup*/ //declared globally
    IfxVadc_Adc_initGroup(&g_VadcAutoScan.adcGroup, &adcGroupConfig);

    /*ADC Channel Init*/
    DrvAdc_Group0ChannelInit(ADC_GROUP0_CH1);
    DrvAdc_Group0ChannelInit(ADC_GROUP0_CH2);
    DrvAdc_Group0ChannelInit(ADC_GROUP0_CH3);

    /*start channel Init*/
    IfxVadc_Adc_startScan(&g_VadcAutoScan.adcGroup);


}

static void DrvAdc_Group0ChannelInit(uint8 param_ChNum)
{
    IfxVadc_Adc_ChannelConfig adcChannelConfigInfo;
    uint32 ulTemp = ((uint32)1u << param_ChNum);

    IfxVadc_Adc_initChannelConfig(&adcChannelConfigInfo, &g_VadcAutoScan.adcGroup);

    adcChannelConfigInfo.channelId  =   (IfxVadc_ChannelId)(param_ChNum);
    adcChannelConfigInfo.resultRegister = (IfxVadc_ChannelResult)(param_ChNum);

    /*Initialize channel*/
    IfxVadc_Adc_initChannel(&adc0Channel[param_ChNum], &adcChannelConfigInfo);

    /*add to scan*/
    IfxVadc_Adc_setScan(&g_VadcAutoScan.adcGroup,ulTemp,ulTemp);

}

void DrvAdc_GetAdcRawGroup0(void)
{
    Ifx_VADC_RES conversionResult;

    /*get Data*/
    conversionResult = IfxVadc_Adc_getResult(&adc0Channel[ADC_GROUP0_CH1]);
    stSensorAdcRaw.UlSSense1_Raw = conversionResult.B.RESULT;

    IfxVadc_Adc_startScan(&g_VadcAutoScan.adcGroup);

  //  conversionResult = IfxVadc_Adc_getResult(&adc0Channel[ADC_GROUP0_CH2]);
   // stSensorAdcRaw.UlSSense2_Raw = conversionResult.B.RESULT;

   // conversionResult = IfxVadc_Adc_getResult(&adc0Channel[ADC_GROUP0_CH3]);
   // stSensorAdcRaw.UlSSense3_Raw = conversionResult.B.RESULT;
}

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
