/**********************************************************************************************************************
 * \file GtmTomPwmHl.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "GtmTomPwmHl.h"
#include "ConfigurationIsr.h"


App_GtmTomPwmHl g_GtmTomPwmHl;
uint32 PWMCnt;



IFX_INTERRUPT(ISR_Timer,0,ISR_PRIORITY_TIMER);


void ISR_Timer(void)
{
    IfxCpu_enableInterrupts();
    IfxGtm_Tom_Timer_acknowledgeTimerIrq(&g_GtmTomPwmHl.drivers.timer);
    g_GtmTomPwmHl.isrCounter.counter++;
}


void GtmTomPwmHl_initTimer(void)
{
    {
        IfxGtm_Tom_Timer_Config timerConfig;
        IfxGtm_Tom_PwmHl_Config pwmHlConfig;
        IfxGtm_Tom_Timer_initConfig (&timerConfig,&MODULE_GTM);
        IfxGtm_Tom_PwmHl_initConfig (&pwmHlConfig);


        timerConfig.base.frequency         =2000;
        timerConfig.base.isrPriority       =ISR_PRIORITY(INTERRUPT_TIMER);
        timerConfig.base.isrProvider       =ISR_PROVIDER(INTERRUPT_TIMER);
        timerConfig.base.minResolution     =(1.0/timerConfig.base.frequency)/1000;
        timerConfig.base.trigger.enabled   =FALSE;
        timerConfig.clock  =IfxGtm_Tom_Ch_ClkSrc_cmuFxclk0;
        timerConfig.base.countDir  =IfxStdIf_Timer_CountDir_upAndDown;

        timerConfig.tom  =IfxGtm_Tom_0;
        timerConfig.timerChannel  =IfxGtm_Tom_Ch_0;
        timerConfig.triggerOut  =&IfxGtm_TOM0_0_TOUT77_P15_6_OUT;

        timerConfig.base.trigger.outputEnabled       =TRUE;
        timerConfig.base.trigger.enabled             =TRUE;
        timerConfig.base.trigger.triggerPoint        =500;
        timerConfig.base.trigger.risingEdgeAtPeriod  =TRUE;

        IfxGtm_Tom_Timer_init(&g_GtmTomPwmHl.drivers.timer,&timerConfig);

        IfxGtm_Tom_ToutMapP ccx[2],coutx[2];
        coutx[0]  = &IfxGtm_TOM0_3_TOUT105_P10_3_OUT;
        ccx[0]    = &IfxGtm_TOM0_4_TOUT22_P33_0_OUT;
        coutx[1]  = &IfxGtm_TOM0_2_TOUT107_P10_5_OUT;
        ccx[1]    = &IfxGtm_TOM0_5_TOUT23_P33_1_OUT;

        pwmHlConfig.timer                 =&g_GtmTomPwmHl.drivers.timer;
        pwmHlConfig.tom                   = timerConfig.tom;
        pwmHlConfig.base.deadtime         =2e-6;
        pwmHlConfig.base.minPulse         =1e-6;
        pwmHlConfig.base.channelCount     = 2;
        pwmHlConfig.base.emergencyEnabled = FALSE;
        pwmHlConfig.base.outputMode       = IfxPort_OutputMode_none;
        pwmHlConfig.base.outputDriver     = IfxPort_PadDriver_cmosAutomotiveSpeed1;
        pwmHlConfig.base.ccxActiveState   = Ifx_ActiveState_high;
        pwmHlConfig.base.coutxActiveState = Ifx_ActiveState_high;
        pwmHlConfig.ccx                   =ccx;
        pwmHlConfig.coutx                 =coutx;

        IfxGtm_Tom_PwmHl_init(&g_GtmTomPwmHl.drivers.pwm,&pwmHlConfig);

        IfxGtm_Tom_Timer_run(&g_GtmTomPwmHl.drivers.timer);
    }
}

void GtmTomPwmHl_init(void)
{
    boolean interruptState = IfxCpu_disableInterrupts();

    Ifx_GTM *gtm = &MODULE_GTM;
    g_GtmTomPwmHl.info.gtmFreq = IfxGtm_Cmu_getModuleFrequency(gtm);
    IfxGtm_enable(gtm);

    IfxGtm_Cmu_setGclkFrequency(&MODULE_GTM,g_GtmTomPwmHl.info.gtmFreq);
    g_GtmTomPwmHl.info.gtmGclkFreq = IfxGtm_Cmu_getGclkFrequency(gtm);

    IfxGtm_Cmu_setClkFrequency(&MODULE_GTM,IfxGtm_Cmu_Clk_0,g_GtmTomPwmHl.info.gtmGclkFreq);
    g_GtmTomPwmHl.info.gtmCmuClk0Freq = IfxGtm_Cmu_getClkFrequency(gtm,IfxGtm_Cmu_Clk_0,TRUE);

    GtmTomPwmHl_initTimer();
    g_GtmTomPwmHl.info.timerValue = IfxGtm_Tom_Timer_getPeriod(&g_GtmTomPwmHl.drivers.timer);
    g_GtmTomPwmHl.tOn[0]=0;
    g_GtmTomPwmHl.tOn[1]=0;

    IfxCpu_restoreInterrupts(interruptState);

    IfxGtm_Cmu_enableClocks(gtm,IFXGTM_CMU_CLKEN_FXCLK | IFXGTM_CMU_CLKEN_CLK0);

}


void GtmTomPwmHl_run(void)
{
    PWMCnt++;
    IfxGtm_Tom_PwmHl *pwmHl = &g_GtmTomPwmHl.drivers.pwm;
    IfxGtm_Tom_Timer *timer = &g_GtmTomPwmHl.drivers.timer;

    g_GtmTomPwmHl.drivers.timer.base.countDir = IfxStdIf_Timer_CountDir_upAndDown;
    IfxGtm_Tom_Timer_getPeriod(timer);
    Ifx_TimerValue DUTY[2];


    DUTY[0]=(uint32)(g_GtmTomPwmHl.tOn[0]*IfxGtm_Tom_Timer_getPeriod(timer));
    DUTY[1]=(uint32)(g_GtmTomPwmHl.tOn[1]*IfxGtm_Tom_Timer_getPeriod(timer));

    IfxGtm_Tom_PwmHl_setMode(pwmHl, Ifx_Pwm_Mode_centerAligned);
    IfxGtm_Tom_Timer_disableUpdate(timer);
    IfxGtm_Tom_PwmHl_setOnTime(pwmHl,DUTY);
    IfxGtm_Tom_Timer_applyUpdate(timer);





}



/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
